### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by dtobi59** [mehdihadeli/awesome-software-architecture#15]
![broken Links](https://user-images.githubusercontent.com/13191454/119240796-ffc17b00-bb06-11eb-99d9-ab2c9d27edf9.JPG)

Clicking on any of the links in the marked area gives a 404 page.

**Comment by loftwah** [comment]
I just noticed that too, it appears to be anything at the top (root) level.

**Comment by dtobi59** [comment]
@loftwah  you're very correct. the links at the sidebar works well.

**Comment by mehdihadeli** [comment]
@dtobi59  I will find a solution for it :)

**Comment by dtobi59** [comment]
@mehdihadeli  I think the problem is: using the ../docs/... path and the .md file extension which is not supported on the web.

**Comment by mehdihadeli** [comment]
> @mehdihadeli I think the problem is: using the ../docs/... path and the .md file extension which is not supported on the web.
Maybe I will remove md in website root.

**Comment by mehdihadeli** [comment]
I remove the table of content form web page, you can use navigation bar. 
I think it is clear now, If you have other suggestion let me know

**Comment by SinghCoder** [comment]
Hey @mehdihadeli , the link for engineering-blogs in left table of contents points to 404, since you removed it from its own separate section in commit https://github.com/mehdihadeli/awesome-software-architecture/commit/12112a39c001dc8cda6fc47736a70d546267de9a and moved to others but the index was not updated.

I am not sure how this index is being generated else, I would have sent a PR, please if possible could you remove the section from the index? or let me know how to do and I would send a PR, whatever is comfortable for you.

**Comment by mehdihadeli** [comment]
@SinghCoder Hi, Thanks for reporting this bug. I removed this section from the sidebar.
